 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  webvid2m_caption: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    vis_processor:
          train:
            name: alpro_video_train
            n_frms: 5
            image_size: 224
            min_scale: 0.9
            max_scale: 1.0
          eval:
            name: alpro_video_eval
            n_frms: 5
            image_size: 224
            min_scale: 0.9
            max_scale: 1.0
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: 
            - https://storage.googleapis.com/sfr-xinstructblip-data-research/data/webvid2m/train.json
            # - /export/home/LAVIS/webvid_annotation.json
          storage: 
            - webvid2m/annotations/train.json
            # - /export/home/LAVIS/webvid_annotation.json
      images:
        storage: /export/video-language-dataset/data/webvid2m/postprocess/downsampled_videos
