 # Copyright (c) 2023, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  audio_video_discrn: 
    # data_dir: ${env.data_dir}/datasets
    audio_processor:
      train:
        name: beats_audio
        n_frames: 2
      eval:
        name: beats_audio
        n_frames: 2
        
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
    
    video_processor:
        train:
          name: alpro_video_train
          n_frms: 2
          image_size: 224
          min_scale: 0.9
          max_scale: 1.0
          full_video: True
        eval:
          name: alpro_video_eval
          n_frms: 2
          image_size: 224
          min_scale: 0.9
          max_scale: 1.0
          full_video: True

    data_type: [video, audio] # [images|videos|features]

    build_info:
      kwargs:
        total: all
        shuffle_modalities: False
        balance_labels: True
        dataset_name: audiocaps
        ground_truth: False
        raw: False

      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        val:
          url: 
            - https://storage.googleapis.com/sfr-xinstructblip-data-research/data/discrn/audiocaps.json
            # - /export/home/LAVIS-xgen_mm/lavis/configs/datasets/discriminatory_reasoning/discriminatory_dataset/audiocaps_discrn.json
          storage: 
            - discrn/annotations/audiocaps.json
            # - /export/home/LAVIS-xgen_mm/lavis/configs/datasets/discriminatory_reasoning/discriminatory_dataset/audiocaps_discrn.json

      audio:
        storage: /export/einstein-vision/audio_datasets/audiocaps/AUDIOCAPS_32000Hz/audio/val
      video:
        storage: /export/einstein-vision/audio_datasets/audiocaps/video/AUDIOCAPS_32000Hz/audio/val