 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: instruct_vicuna7b
  load_finetuned: False
  load_pretrained: True
   
  pretrained: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/InstructBLIP/instruct_blip_vicuna7b_trimmed.pth" #"/exports/eddie/scratch/v1hhu/LAVIS_1/lavis/output/instructblip/vqa_base_vicuna7b_val/20240124223/checkpoint_4.pth" #20240106225/checkpoint_2.pth" #/20240124135/checkpoint_4.pth"  #vqa_describe_vicuna7b_val/20240105160/checkpoint_2.pth" #20240105110/checkpoint_2.pth" #vqa_describe_vicuna7b_val/20240105160/checkpoint_2.pth" #vqa_merge_vicuna7b_val/20240111224/checkpoint_2.pth" #vqa_base_vicuna7b_val/20240106225/checkpoint_2.pth" #  vqa_base_vicuna7b_val/20240105110/checkpoint_2.pth" #"/exports/eddie/scratch/v1hhu/LAVIS/lavis/output/instructblip/vqa_describe_vicuna7b_val/20240105160/checkpoint_2.pth" #"/exports/eddie/scratch/v1hhu/LAVIS/lavis/output/instructblip/vqa_describe_vicuna7b_val/20240105160/checkpoint_1.pth" #"https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/InstructBLIP/instruct_blip_vicuna7b_trimmed.pth" #"/exports/eddie/scratch/v1hhu/LAVIS/lavis/output/instructblip/coco_captioning_vicuna7b_val/20231220134/checkpoint_2.pth" #"/exports/eddie/scratch/v1hhu/LAVIS/lavis/output/instructblip/vqa_base_vicuna7b_val/20231224134/checkpoint_2.pth" #"https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/InstructBLIP/instruct_blip_vicuna7b_trimmed.pth"
  finetuned: ""

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True

  # Q-Former
  num_query_token: 32

  # path to Vicuna checkpoint
  llm_model: "/exports/eddie/scratch/v1hhu/vicuna-7b-v1.1"

  # generation configs
  prompt: ""


preprocess:
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 224
        eval:
          name: "blip_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
