 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  modelnet40_cls: # name of the dataset builder
    data_type: [pc, images] 

    vis_processor:
      train:
        name: "clip_image_train"
        image_size: 224
      eval:
        name: "clip_image_eval"
        image_size: 224
      
    pc_processor:
        train:
          name: "ulip_pc"
        eval:
          name: "ulip_pc"
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: 
            - https://storage.googleapis.com/sfr-ulip-code-release-research/modelnet40_normal_resampled/modelnet40_shape_names.txt
            - https://storage.googleapis.com/sfr-ulip-code-release-research/modelnet40_normal_resampled/modelnet40_train_8192pts_fps.dat
            - https://storage.googleapis.com/sfr-ulip-code-release-research/modelnet40_normal_resampled/modelnet40_train.txt
          storage: 
            - modelnet40_normal_resampled/modelnet40_shape_names.txt
            - modelnet40_normal_resampled/modelnet40_train_8192pts_fps.dat
            - /modelnet40_normal_resampled/modelnet40_train.txt
        val:
          url: 
            - https://storage.googleapis.com/sfr-ulip-code-release-research/modelnet40_normal_resampled/modelnet40_shape_names.txt
            - https://storage.googleapis.com/sfr-ulip-code-release-research/modelnet40_normal_resampled/modelnet40_test_8192pts_fps.dat
            - https://storage.googleapis.com/sfr-ulip-code-release-research/modelnet40_normal_resampled/modelnet40_test.txt
          storage: 
            - modelnet40_normal_resampled/modelnet40_shape_names.txt
            - modelnet40_normal_resampled/modelnet40_test_8192pts_fps.dat
            - modelnet40_normal_resampled/modelnet40_test.txt
      
      pc:
        storage: /export/home/ULIP/data/modelnet40_normal_resampled
      
      images:
        storage: /export/einstein-vision/3d_vision/3d_object_datasets/modelnet40_pc_img