 # Copyright (c) 2023, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  vsr_classification_instruct:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    vis_processor:
      train:
        name: "clip_image_train"
        image_size: 224
      eval:
        name: "clip_image_eval"
        image_size: 224

    text_processor:
      train:
        name: blip_caption
      eval:
        name: blip_caption

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
        train:
          url:
              - https://storage.googleapis.com/sfr-xinstructblip-data-research/data/vsr/train.jsonl
              # - /export/home/data/annotations/VSR/visual-spatial-reasoning/data/splits/zeroshot/train.jsonl
          storage:
              - vsr/annotations/train.jsonl
              # - /export/home/data/annotations/VSR/visual-spatial-reasoning/data/splits/zeroshot/train.jsonl
        val:
          url:
              - https://storage.googleapis.com/sfr-xinstructblip-data-research/data/vsr/dev.jsonl
              # - /export/home/data/annotations/VSR/visual-spatial-reasoning/data/splits/zeroshot/dev.jsonl
          storage:
              - vsr/annotations/dev.jsonl
              # - /export/home/data/annotations/VSR/visual-spatial-reasoning/data/splits/zeroshot/dev.jsonl
        test:
          url:
              - https://storage.googleapis.com/sfr-xinstructblip-data-research/data/vsr/test.jsonl
              # - /export/home/data/annotations/VSR/visual-spatial-reasoning/data/splits/zeroshot/test.jsonl
          storage:
              - vsr/annotations/test.jsonl
              # - /export/home/data/annotations/VSR/visual-spatial-reasoning/data/splits/zeroshot/test.jsonl
      images:
          storage: /export/share/datasets/vision_language/VSR/images
