 # Copyright (c) 2023, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  vlep_caption: # 4900
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]

    vis_processor:
        train:
          name: alpro_video_train
          n_frms: 4
          image_size: 224
          min_scale: 0.9
          max_scale: 1.0
          full_video: False
        eval:
          name: alpro_video_eval
          n_frms: 4
          image_size: 224
          min_scale: 0.9
          max_scale: 1.0
          full_video: False
    
    text_processor:
      train:
        name: blip_caption
      eval:
        name: blip_caption

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: 
            - https://storage.googleapis.com/sfr-xinstructblip-data-research/data/vlep/annotations_train_existing.json
            # - /export/video-language-dataset/data/vlep/annotations/annotations_train_existing.json
          storage: 
            - vlep/annotations/annotations_train_existing.json
            # - /export/video-language-dataset/data/vlep/annotations/annotations_train_existing.json
        val:
          url: 
            - https://storage.googleapis.com/sfr-xinstructblip-data-research/data/vlep/annotations_dev_existing.json
            # - /export/video-language-dataset/data/vlep/annotations/annotations_dev_existing.json
          storage:  
            - vlep/annotations/annotations_dev_existing.json
            # - /export/video-language-dataset/data/vlep/annotations/annotations_dev_existing.json
      videos:
        storage: /export/video-language-dataset/data/vlep/videos
