 # Copyright (c) 2023, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  conceptual_caption_3m_instruct:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    vis_processor:
      train:
        name: "clip_image_train"
        image_size: 224
      eval:
        name: "clip_image_eval"
        image_size: 224
    
    text_processor:
      train:
        name: blip_instruction
        task: caption
        modality: image
      eval:
        name: blip_caption

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url:
              - /export/home/workspace/datasets/cc3m.json
          storage:
              - conceptual_caption/annotations/cc3m.json
      images:
          storage: conceptual_caption/images
